### ISSUE TITLE
Projections?

### ISSUE THREAD

**Issue by blissi** [snatalenko/node-cqrs#1]
Hallo,
I'm wondering how projections actually work. I had a look at the source code and was playing around a bit, but couldn't make sense of it.

Say, I have a web application and am restarting the server. Now all events are restored from the event store into the projection.

The problem I have is: how do I know when all events have been restored in a projection? Everything is called under the hood by the container and it would not be good to send each event to the client via websocket. I would like to have a single entry point that's called when all events have been processed.

I also tried to override the restore-function and do something when the promise of the base-implementation has been resolved. That didn't work either because the handlers seem to be called asynchronously, after the restore-promise has finished.

Maybe I have overlooked something obvious. Can you clarify this to me?

Greetings,
Steven

**Comment by snatalenko** [comment]
Hi Steven, 

Thank you for your question and sorry for a such slow response. I've moved the documentation to gitbook and briefly described how the Projections work, you can find it here: https://snatalenko.gitbooks.io/node-cqrs/content/Entities/Projection/

I know this part with the views is not perfect, so I would love to hear a suggestion on how it can be improved. 

Thanks,
Stas

**Comment by TomKaltz** [comment]
Is there a plan for a persisted projection store?

**Comment by snatalenko** [comment]
Yes, that's the next major feature I'll be working on, but I don't have an ETA yet. Probably, a few months from now.
