### ISSUE TITLE
Status of ts branch

### ISSUE THREAD

**Issue by TomKaltz** [snatalenko/node-cqrs#20]
Hi can you let us know the status of the “ts” branch?

**Comment by snatalenko** [comment]
Hi @TomKaltz,
After migrating to TypeScript and making a few minor changes I noticed that there're concurrency-related issues in the events distribution mechanism. Basically, same event can be delivered to an aggregate twice - thru the `eventStore.publish` and thru `eventStore.getAggregateEvents`. You can see that by running the integration tests - they're failing on the `ts` branch. Same issue exist on the main branch, but it's more difficult to reproduce. That's the only one I want to fix before merging the `ts` into `master`.
